config:
  credentials: []
  project_repos:
    github.com/Deltares/hydromt_sfincs:
      branch: main
      repo: https://github.com/Deltares/hydromt_sfincs
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Deltares/hydromt_sfincs git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-azure-stoat.sh
        container: qc.acc_tasty-saffron-heron
  QC.Doc:
    repos:
      github.com/Deltares/hydromt_sfincs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-charcoal-mule.sh
        container: qc.doc_homely-mauve-cow
      github.com/Deltares/hydromt_sfincs git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-purple-bombay.sh
        container: qc.doc_ready-auburn-fowl
      github.com/Deltares/hydromt_sfincs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-rose-camel.sh
        container: qc.doc_slaphappy-denim-alligator
      github.com/Deltares/hydromt_sfincs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-orchid-iguana.sh
        container: qc.doc_greasy-corn-dragonfly
  QC.Lic:
    repos:
      github.com/Deltares/hydromt_sfincs licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-amethyst-antelope.sh
        container: qc.lic_leaky-chestnut-jaguar
  QC.Sec:
    repos:
      github.com/Deltares/hydromt_sfincs bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ivory-axolotl.sh
        container: qc.sec_leaky-charcoal-civet
  QC.Sty:
    repos:
      github.com/Deltares/hydromt_sfincs flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-beige-emu.sh
        container: qc.sty_freaky-brass-gerbil
      github.com/Deltares/hydromt_sfincs jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-vermilion-salamander.sh
        container: qc.sty_snazzy-dandelion-abyssinian
  QC.Uni:
    repos:
      github.com/Deltares/hydromt_sfincs pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-yellow-albatross.sh
        container: qc.uni_foggy-amaranth-rabbit
  QC.Ver:
    repos:
      github.com/Deltares/hydromt_sfincs get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-olive-tetra.sh
        container: qc.ver_skinny-mauve-crab
timeout: 5400
